cors:
  originPatterns: http://localhost:8080, http://localhost:3000, http://localhost:4200, https://github.com/gomes-tkd

file:
  upload-dir: ${UPLOAD_DIR:${user.home}/Desktop/project/uploads-files/java/spring-rest-mysql-udemy/}

spring:
  application:
    name: rest-with-spring-boot-and-java

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: gomes-tkd
    password: admin123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate: {}
    show-sql: false
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

logging:
  level:
    root: INFO

spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
